### ISSUE TITLE
Retrieve list of activity types that are utilising the QBank API

### ISSUE THREAD

**Issue by 3ark91** [safatshahin/moodle-qbank_qtoactivity#13]
As per the requirements we will need a function to retrieve the activity types that utilise the qbank API. These activities will need to be displayed to the user within the modal form to allow them to select the desired activity type

**Comment by safatshahin** [comment]
This will be a discovery work, we might end up getting that it's impossible.

Different discussion:
If you cant, we might look at a settings page or a page with fields where people will be able to add the plugins.

**Comment by hacampbell** [comment]
For getting a list of all declared classes and checking is one class is a sub class of another https://stackoverflow.com/questions/6671398/get-all-defined-classes-of-a-parent-class-in-php

Using a SQL Query to get a list of the quizzes in moodle https://moodle.org/mod/forum/discuss.php?d=424410

---

#### Most promising find so far
https://github.com/moodle/moodle/blob/master/lib/modinfolib.php
The function `get_array_of_activities` can be used to get a list of all the activities in a given course. It requires a course object as its first parameter, but I've got no idea how to give it that. This looks very promising though.
