### ISSUE TITLE
Documentation responsibility

### ISSUE THREAD

**Issue by 3ark91** [safatshahin/moodle-qbank_qtoactivity#4]
Safat mentioned that we will need to decide how to handle the production of documentation for the project. Do we take turns? Are we responsible for our own documentation? Or is one of us a big fan of producing documentation and wants to take it all on? (somehow i doubt it haha)

**Comment by Jhojji** [comment]
I'd say we all just document what we do when we do it? I'm not sure of the exact details of how and when we should document things, whether just in the read me file or as separate files, but for the most part it shouldn't be too much effort to document things as we go. If you'd like someone else to document something, we can always open up an issue for it.

**Comment by 3ark91** [comment]
Yeah I would agree - it is easiest for the code writer to document the code because they're the one who knows it best. Plus it gives us all practice at documentation.
